alias ls='ls --color=auto'
alias diff='diff --color'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rg='rg -L --max-depth=25 --smart-case'

alias sshrc='sshrc -X'

alias sshconnor='sshrc root@176.9.7.113'
alias sshclockpi='sshrc pi@clockpi.local'
alias sshcvbackend='sshrc -i ~/.ssh/keys/root@176.9.7.113 webdev@49.13.127.233'

alias sshpve01='sshrc root@192.168.2.230'
alias sshpve02='sshrc root@192.168.2.231'
alias sshpve03='sshrc root@192.168.2.232'
alias sshkb='sshrc webdev@2a02:a44b:8910:1::101'
alias sshmedia='sshrc webdev@2a02:a44b:8910:1::102'
alias sshjenkins='sshrc webdev@2a02:a44b:8910:1::103'
alias sshvarnish='sshrc webdev@2a02:a44b:8910:1::106'
alias sshcv='sshrc webdev@2a02:a44b:8910:1::107'
alias sshestimate='sshrc webdev@2a02:a44b:8910:1::110'

alias lll='lsd -lah | less'
alias ll='lsd -lah'
alias la='lsd -A'
alias l='lsd -F'
alias glog='git log --graph --pretty="format:%C(yellow)%h%Cred%d%Creset %s %C(white) %C(cyan)%an%Creset, %C(green)%ar%Creset"'
alias c='clear && . $HOME/.zshrc'
alias :q='exit'
alias ..='cd ..'
alias .='source'
alias t='tmux'
alias tsess='tmux new-session -A -s remote'
alias cdgit='cd $(git root)'

alias copy='xclip -selection clipboard'
alias vi='nvim'
alias vim='nvim'
alias iv='nvim'
alias v='nvim'
alias gti='git'
alias nvimrc='nvim ~/.config/nvim/init.lua'
alias nvimdiff='git -c "diff.tool=nvimdiff" difftool'

# Edit this file.
alias aliases='vi $HOME/.config/zsh/config/aliases.zsh'
